<?php
declare(strict_types=1);

return [
    'bootstrap_admins' => [
        'a@asx.mx',
    ],
    'roles' => [
        'regular' => [
            'label' => 'Usuario regular',
            'menu_label' => 'Menú del usuario',
            'role_copy' => 'Tu espacio está enfocado en herramientas operativas, ejecución comercial y formación.',
            'helper_copy' => 'Todos los usuarios nuevos entran como usuario regular hasta que un administrador les asigne un rol superior.',
        ],
        'admin' => [
            'label' => 'Administrador',
            'menu_label' => 'Menú de administración',
            'role_copy' => 'Tienes acceso a las áreas de contenido y estructura del sitio que no verá el usuario regular.',
            'helper_copy' => 'El correo a@asx.mx funciona como primer admin bootstrap. Los siguientes admins deberían marcarse de forma segura en app_metadata.role = admin.',
        ],
    ],
    'menus' => [
        'regular' => [
            [
                'id' => 'validar-mercado',
                'label' => 'Validar Mercado',
                'short_label' => 'Mercado',
                'icon' => 'travel_explore',
                'accent' => 'blue',
                'fab_label' => 'Nueva validación',
                'kicker' => 'Investigación comercial',
                'description' => 'Aquí iremos concentrando herramientas para confirmar demanda, competencia, mensajes y oportunidad real antes de lanzar una oferta.',
                'placeholder_title' => 'Módulo de validación de mercado',
                'placeholder_copy' => 'Este espacio será la base para analizar nichos, detectar objeciones y validar si una oportunidad merece más inversión.',
                'feature_highlights' => [
                    ['title' => 'Señales de demanda', 'copy' => 'Detecta interés real antes de construir o vender.'],
                    ['title' => 'Mapa competitivo', 'copy' => 'Ubica referentes, precios y huecos de mercado.'],
                    ['title' => 'Insight accionable', 'copy' => 'Convierte observaciones en una decisión clara.'],
                ],
            ],
            [
                'id' => 'crear-oferta',
                'label' => 'Crear Oferta',
                'short_label' => 'Oferta',
                'icon' => 'deployed_code',
                'accent' => 'red',
                'fab_label' => 'Nueva oferta',
                'kicker' => 'Propuesta de valor',
                'description' => 'Diseñaremos aquí la estructura de la oferta, el ángulo comercial y la promesa principal para cada solución.',
                'placeholder_title' => 'Constructor de ofertas',
                'placeholder_copy' => 'La idea es aterrizar producto, promesa, bonos y diferenciadores con ayuda de IA y plantillas accionables.',
                'feature_highlights' => [
                    ['title' => 'Promesa central', 'copy' => 'Define con claridad qué resultado vendes y para quién.'],
                    ['title' => 'Bonos y stacks', 'copy' => 'Organiza valor percibido sin complicar la venta.'],
                    ['title' => 'Mensajes listos', 'copy' => 'Genera argumentos y textos comerciales consistentes.'],
                ],
            ],
            [
                'id' => 'acelerar-ventas',
                'label' => 'Acelerar Ventas',
                'short_label' => 'Ventas',
                'icon' => 'bolt',
                'accent' => 'yellow',
                'fab_label' => 'Nuevo impulso',
                'kicker' => 'Crecimiento comercial',
                'description' => 'Este módulo se enfocará en scripts, seguimiento, objeciones, automatizaciones ligeras y activadores para cerrar más rápido.',
                'placeholder_title' => 'Motor para acelerar ventas',
                'placeholder_copy' => 'Aquí iremos uniendo automatización comercial, priorización de leads y mejoras de conversión en cada etapa.',
                'feature_highlights' => [
                    ['title' => 'Seguimiento inteligente', 'copy' => 'Ordena prioridades y próximos pasos con contexto.'],
                    ['title' => 'Objeciones resueltas', 'copy' => 'Convierte bloqueos comunes en respuestas claras.'],
                    ['title' => 'Más cierres', 'copy' => 'Empuja velocidad sin perder control del proceso.'],
                ],
            ],
            [
                'id' => 'escalar-operacion',
                'label' => 'Escalar Operación',
                'short_label' => 'Operación',
                'icon' => 'settings_slow_motion',
                'accent' => 'green',
                'fab_label' => 'Nuevo flujo',
                'kicker' => 'Sistema interno',
                'description' => 'Aquí vivirán las herramientas para estandarizar procesos, automatizar tareas y multiplicar capacidad operativa.',
                'placeholder_title' => 'Centro para escalar operación',
                'placeholder_copy' => 'La meta es que cada flujo importante del negocio pueda repetirse mejor, más rápido y con menos fricción.',
                'feature_highlights' => [
                    ['title' => 'Procesos repetibles', 'copy' => 'Documenta y mejora pasos críticos del negocio.'],
                    ['title' => 'Automatización útil', 'copy' => 'Reduce trabajo manual sin perder visibilidad.'],
                    ['title' => 'Capacidad ampliada', 'copy' => 'Haz más con el mismo equipo y mejor control.'],
                ],
            ],
            [
                'id' => 'academia-ia',
                'label' => '🎓 Academia IA',
                'short_label' => 'Academia',
                'icon' => 'school',
                'accent' => 'blue',
                'fab_label' => 'Nuevo aprendizaje',
                'kicker' => 'Formación continua',
                'description' => 'La academia será el espacio de capacitación, rutas de aprendizaje, playbooks y entrenamiento para dominar cada herramienta.',
                'placeholder_title' => 'Campus de aprendizaje AiScaler',
                'placeholder_copy' => 'Aquí podrás organizar cursos, rutas y lecciones para que el usuario aprenda dentro del mismo ecosistema.',
                'feature_highlights' => [
                    ['title' => 'Rutas guiadas', 'copy' => 'Aprendizaje estructurado para avanzar sin perderse.'],
                    ['title' => 'Playbooks aplicados', 'copy' => 'Material listo para pasar de teoría a ejecución.'],
                    ['title' => 'Progreso medible', 'copy' => 'Seguimiento claro del avance dentro de la academia.'],
                ],
            ],
        ],
        'admin' => [
            [
                'id' => 'paginas-del-sitio',
                'label' => 'Páginas del sitio',
                'short_label' => 'Páginas',
                'icon' => 'web',
                'accent' => 'blue',
                'fab_label' => 'Nueva página',
                'kicker' => 'Contenido web',
                'description' => 'Desde aquí el admin podrá gestionar páginas públicas, landings y secciones estratégicas del sitio.',
                'placeholder_title' => 'Administrador de páginas',
                'placeholder_copy' => 'Este módulo será la puerta para editar estructura visual, copys y bloques que el usuario regular nunca verá.',
                'feature_highlights' => [
                    ['title' => 'Landings clave', 'copy' => 'Controla las páginas más importantes del sitio.'],
                    ['title' => 'Bloques editables', 'copy' => 'Actualiza secciones sin tocar el flujo del usuario.'],
                    ['title' => 'Visibilidad pública', 'copy' => 'Define qué contenido sale a producción.'],
                ],
            ],
            [
                'id' => 'entradas-del-blog',
                'label' => 'Entradas del blog',
                'short_label' => 'Blog',
                'icon' => 'article',
                'accent' => 'red',
                'fab_label' => 'Nueva entrada',
                'kicker' => 'Contenido editorial',
                'description' => 'Aquí vivirán las herramientas para crear, editar y publicar entradas del blog y su catálogo editorial.',
                'placeholder_title' => 'Gestor editorial del blog',
                'placeholder_copy' => 'La idea es concentrar borradores, categorías, SEO y publicación en un solo panel exclusivo de admin.',
                'feature_highlights' => [
                    ['title' => 'Borradores y publicación', 'copy' => 'Controla el ciclo completo de cada artículo.'],
                    ['title' => 'Categorías y orden', 'copy' => 'Mantén coherencia editorial y navegación clara.'],
                    ['title' => 'Contenido con intención', 'copy' => 'Diseña piezas que atraigan tráfico y conviertan.'],
                ],
            ],
            [
                'id' => 'cursos',
                'label' => 'Cursos',
                'short_label' => 'Cursos',
                'icon' => 'menu_book',
                'accent' => 'green',
                'fab_label' => 'Nuevo curso',
                'kicker' => 'Academia y catálogo',
                'description' => 'Este espacio servirá para crear cursos, organizar módulos y decidir qué verá el alumno dentro de la academia.',
                'placeholder_title' => 'Gestión de cursos',
                'placeholder_copy' => 'Aquí se administrarán cursos, lecciones y catálogo formativo para alimentar la Academia IA.',
                'feature_highlights' => [
                    ['title' => 'Catálogo formativo', 'copy' => 'Organiza cursos, módulos y lecciones.'],
                    ['title' => 'Experiencia del alumno', 'copy' => 'Controla lo que cada usuario puede ver.'],
                    ['title' => 'Escalabilidad educativa', 'copy' => 'Prepara la academia para crecer sin caos.'],
                ],
            ],
        ],
    ],
];
